/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package compressor_decompressor;
import javax.swing.*;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Shrutika
 */
public class AppJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AppJFrame
     */
    public AppJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compress = new javax.swing.JLabel();
        decompress = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 506));
        setTitle(" File Compressor/Decompressor");
        ImageIcon logo = new ImageIcon("src/photos/logo.png");
        setIconImage(logo.getImage());
        setMinimumSize(new java.awt.Dimension(900, 506));
        setResizable(false);
        getContentPane().setLayout(null);

        compress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/CompressButton.png"))); // NOI18N
        compress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compressMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compressMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compressMouseExited(evt);
            }
        });
        getContentPane().add(compress);
        compress.setBounds(120, 180, 200, 248);

        decompress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/DecompressButton.png"))); // NOI18N
        decompress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decompressMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decompressMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decompressMouseExited(evt);
            }
        });
        getContentPane().add(decompress);
        decompress.setBounds(570, 180, 200, 248);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 506);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void compressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compressMouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==compress){
            JFileChooser filechooser = new JFileChooser();
            int response =filechooser.showSaveDialog(null);
            if(response==JFileChooser.APPROVE_OPTION){
                File file = new File(filechooser.getSelectedFile().getAbsolutePath());
                System.out.print(file);
                try{
                    Compressor.method(file);
                }
                catch(IOException ee){
                    JOptionPane.showMessageDialog(null, ee.toString());
                }
            }
        }
    }//GEN-LAST:event_compressMouseClicked

    private void decompressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decompressMouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==decompress){
            JFileChooser filechooser = new JFileChooser();
            int response =filechooser.showSaveDialog(null);
            if(response==JFileChooser.APPROVE_OPTION){
                File file = new File(filechooser.getSelectedFile().getAbsolutePath());
                System.out.print(file);
                try{
                    Decompressor.method(file);
                }
                catch(Exception ee){
                    JOptionPane.showMessageDialog(null, ee.toString());
                }
            }
        }
    }//GEN-LAST:event_decompressMouseClicked

    private void compressMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compressMouseEntered
        // TODO add your handling code here:
        compress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/CompressButtonHover.png")));
    }//GEN-LAST:event_compressMouseEntered

    private void compressMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compressMouseExited
        // TODO add your handling code here:
        compress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/CompressButton.png")));
    }//GEN-LAST:event_compressMouseExited

    private void decompressMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decompressMouseEntered
        // TODO add your handling code here:
        decompress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/DecompressButtonHover.png")));
    }//GEN-LAST:event_decompressMouseEntered

    private void decompressMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decompressMouseExited
        // TODO add your handling code here:
        decompress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/DecompressButton.png")));
    }//GEN-LAST:event_decompressMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AppJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel compress;
    private javax.swing.JLabel decompress;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
